server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true

spring:
  application:
    name: child_tracking
  profiles:
    active: dev
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: sandbox.smtp.mailtrap.io
            protocols: TLSv1.2
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: uz.hojiakbar.child_tracking.controller


logging:
  level:
    com.zaxxer.hikari: WARN
    org.hibernate:
      SQL: ERROR
      type:
        descriptor:
          sql:
            BasicBinder: ERROR