spring.datasource.url=jdbc:postgresql://localhost:5432/child_tracking_db
spring.datasource.username=your_username
spring.datasource.password=your_password
jwt.secret=your_jwt_secret_min_32_chars
spring.mail.username=your_mail_username
spring.mail.password=your_mail_password
spring.mail.from=noreply@yourdomain.com

